name: dvm
version: 0.0.0-alpha
description: Manage multiple active Dart versions.
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/dvm

environment:
  sdk: '>=1.22.0 <2.0.0'

dependencies:
  archive: ^1.0.20
  args: ^0.13.7
  func: ^1.0.0
  logging: ^0.11.0
  meta: ^1.0.5
  path: ^1.0.0
  pub_semver: ^1.3.2
  stack_trace: ^1.7.0
  stream_transform: ^0.0.4

executables:
  dvm:
